require("user.options")
require("user.keymaps")
require("user.plugins")

vim.g.did_load_filetypes = 1

require("user.colorscheme")
require("user.devicons")
require("user.treesitter")
require("user.lsp")
require("user.cmp")
require("user.telescope")
require("user.autopairs")
require("user.comment")
require("user.indentline")
require("user.impatient")
require("user.transparent")
require("user.flutter")
require("user.lualine")
require("user.toggleterm")
