require("config.telescope")
require("config.nvim_lsp")
require("config.nvim_treesitter")
require("config.nvim_cmp")
require("config.sets")
require("config.key_mappings")
-- require("config.tab_status_line")
-- require("config.dev")
